# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('answer_id', models.IntegerField()),
                ('keyword', models.CharField(max_length=20)),
                ('understand_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=32)),
                ('created_on', models.DateTimeField()),
                ('checked_on', models.DateTimeField()),
                ('task_type', models.IntegerField(default=0)),
                ('annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='annotator.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=20)),
                ('downvotes', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('flags', models.IntegerField(default=0)),
                ('start_time', models.CharField(blank=True, max_length=16)),
                ('description', models.CharField(default=b'Explanation', max_length=20)),
                ('annotation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Annotation')),
            ],
        ),
    ]
