# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='location',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='stackID',
            new_name='questionID',
        ),
        migrations.AddField(
            model_name='annotation',
            name='answerID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation',
            field=models.URLField(),
        ),
    ]
