# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='keyword',
        ),
        migrations.AddField(
            model_name='annotation',
            name='phrase',
            field=models.TextField(default='-stackannotator-temp-'),
            preserve_default=False,
        ),
    ]
