# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_auto_20160912_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='answerID',
            new_name='answer_id',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='questionID',
            new_name='question_id',
        ),
    ]
