# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_auto_20160913_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation',
            field=models.URLField(blank=True),
        ),
    ]
