# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0004_auto_20160914_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='keyword',
            field=models.CharField(default='fail', max_length=20),
            preserve_default=False,
        ),
    ]
