# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0005_annotation_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20)),
                ('downvotes', models.IntegerField()),
                ('upvotes', models.IntegerField()),
                ('flag', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='annotation',
        ),
        migrations.AddField(
            model_name='video',
            name='annotation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Annotation'),
        ),
    ]
