# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0006_auto_20160922_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=32)),
                ('created_on', models.DateTimeField()),
                ('checked_on', models.DateTimeField()),
                ('annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='annotator.Annotation')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='flag',
        ),
        migrations.AddField(
            model_name='video',
            name='flags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='start_time',
            field=models.CharField(default=b'0:00', max_length=16),
        ),
        migrations.AlterField(
            model_name='video',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
