# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0007_auto_20160923_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='position',
        ),
    ]
