# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0009_auto_20160928_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='understand_count',
            field=models.IntegerField(default=0),
        ),
    ]
