# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0010_annotation_understand_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.IntegerField(default=0),
        ),
    ]
