# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0011_auto_20161022_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='description',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(default=b'Youtube', max_length=20),
        ),
    ]
